name: Deploy to AWS S3 Bucket
on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} ## SETUP Secrets ON GITHUB
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} ## SETUP Secrets ON GITHUB
          aws-region: us-east-2 ## CHANGE

      - name: Sync files to S3 bucket
        run: aws s3 sync ./dist s3://skscorekeeper.jeffpodmayer.com --delete

      - name: Invalidate CloudFront Cache
        run: aws cloudfront create-invalidation --distribution-id E2WRTCWFK2CSFD --paths "/*"
